### ISSUE TITLE
视频资源地址

### ISSUE THREAD

**Issue by szhang6** [ruanwenjun/firstproject#2]
请问一下，现在还有这些视频的地址吗，可否分享一下？有的细节想听一下，多谢：）

**Comment by ruanwenjun** [comment]
ok,百度云账号发我一下，我邮箱bestruanwenjun@gmail.com

**Comment by ruanwenjun** [comment]
@szhang6 百度云账号发我一下,我邮箱bestruanwenjun@gmail.com

**Comment by szhang6** [comment]
抱歉没有及时看到，已发送到您邮箱了

**Comment by szhang6** [comment]
xiaoxipeter@163.com
如果邮件没有发送成功，也可以用上面这个邮件
